drop table JOB if exists;

create table JOB (ID bigint generated by default as identity (start with 1), TITLE varchar(255), FUNCTION varchar(255), STATE varchar(255), COUNTRY varchar(255), DESCRIPTION varchar(255), POSTED_DATE date, primary key (id))
